ACCESS_TOKEN: '41080440-qjZ1Jl4Ua61IXtvN4WSxUnm3RoxEaBHYGkOWLqQQO'
ACCESS_SECRET: 'aCKVeUDUIuxp9ZpFPmZWpbdOfq4N1LDKSQohTUsIhngIh'
CONSUMER_KEY: '75bNvkIXnOFPKqU44O9ClIjNR'
CONSUMER_SECRET: '89Es022ydnPadYRBm9F7lC8NaW1XhgmT7xjbV0UQhs673Si2iN'
all_cols: ["Variables",
"Date",
"Time",
"Type",
"Hashtag 0/1",
"Hashtag #",
"Specific Hashtag",
"0/1 @",
"# @",
"Specific @",
"Tweet content",
"Link Title",
"Article Content in the Tweet",
"Link",
"Link 0/1",
"# links",
"link works",
"link to news website",
"Website Type",
"Social Media Type",
"Retweeted/Quoted @",
"Illustration",
"Illustration Type",
"Hashtag game",
"News phrase",
"Sensational phrase",
"Local",
"Regional",
"National",
"International",
"Traffic",
"Weather regular",
"Weather extreme",
"Crime",
"Events",
"Lifestyle",
"Entertainment",
"Sports",
"Education",
"Politics",
"City hall",
"Statehouse",
"Courthouse",
"Economy",
"Business",
"Stock Exchange",
"Health",
"Science",
"Technology",
"Travel",
"Leisure",
"Obituaries",
"Abortion",
"2nd Amenments",
"Immigration",
"Police brutality",
"Terrorism",
"Race",
"Gender",
"Religion",
"Russian Sphere",
"Discredit institutions",
"Discredit media",
"Unclear",
"Filler",
"Other topic",
"Informative",
"Fearmongering",
"Provocative",
"Reflexive portrayal"]